// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buffer.proto

package grpcBuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector2Int struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2Int) Reset()         { *m = Vector2Int{} }
func (m *Vector2Int) String() string { return proto.CompactTextString(m) }
func (*Vector2Int) ProtoMessage()    {}
func (*Vector2Int) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{0}
}

func (m *Vector2Int) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2Int.Unmarshal(m, b)
}
func (m *Vector2Int) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2Int.Marshal(b, m, deterministic)
}
func (m *Vector2Int) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2Int.Merge(m, src)
}
func (m *Vector2Int) XXX_Size() int {
	return xxx_messageInfo_Vector2Int.Size(m)
}
func (m *Vector2Int) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2Int.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2Int proto.InternalMessageInfo

func (m *Vector2Int) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector2Int) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Node struct {
	PosArray             *Vector2Int `protobuf:"bytes,1,opt,name=posArray,proto3" json:"posArray,omitempty"`
	Player               int32       `protobuf:"varint,2,opt,name=player,proto3" json:"player,omitempty"`
	Captered             bool        `protobuf:"varint,3,opt,name=captered,proto3" json:"captered,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetPosArray() *Vector2Int {
	if m != nil {
		return m.PosArray
	}
	return nil
}

func (m *Node) GetPlayer() int32 {
	if m != nil {
		return m.Player
	}
	return 0
}

func (m *Node) GetCaptered() bool {
	if m != nil {
		return m.Captered
	}
	return false
}

type InitGameRequest struct {
	Board                []*Node  `protobuf:"bytes,1,rep,name=board,proto3" json:"board,omitempty"`
	GameId               string   `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitGameRequest) Reset()         { *m = InitGameRequest{} }
func (m *InitGameRequest) String() string { return proto.CompactTextString(m) }
func (*InitGameRequest) ProtoMessage()    {}
func (*InitGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{2}
}

func (m *InitGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitGameRequest.Unmarshal(m, b)
}
func (m *InitGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitGameRequest.Marshal(b, m, deterministic)
}
func (m *InitGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitGameRequest.Merge(m, src)
}
func (m *InitGameRequest) XXX_Size() int {
	return xxx_messageInfo_InitGameRequest.Size(m)
}
func (m *InitGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitGameRequest proto.InternalMessageInfo

func (m *InitGameRequest) GetBoard() []*Node {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *InitGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type InitGameResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitGameResponse) Reset()         { *m = InitGameResponse{} }
func (m *InitGameResponse) String() string { return proto.CompactTextString(m) }
func (*InitGameResponse) ProtoMessage()    {}
func (*InitGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{3}
}

func (m *InitGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitGameResponse.Unmarshal(m, b)
}
func (m *InitGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitGameResponse.Marshal(b, m, deterministic)
}
func (m *InitGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitGameResponse.Merge(m, src)
}
func (m *InitGameResponse) XXX_Size() int {
	return xxx_messageInfo_InitGameResponse.Size(m)
}
func (m *InitGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitGameResponse proto.InternalMessageInfo

func (m *InitGameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PlayedAIRequest struct {
	CurrentPlayerMove    *Node    `protobuf:"bytes,2,opt,name=currentPlayerMove,proto3" json:"currentPlayerMove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayedAIRequest) Reset()         { *m = PlayedAIRequest{} }
func (m *PlayedAIRequest) String() string { return proto.CompactTextString(m) }
func (*PlayedAIRequest) ProtoMessage()    {}
func (*PlayedAIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{4}
}

func (m *PlayedAIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayedAIRequest.Unmarshal(m, b)
}
func (m *PlayedAIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayedAIRequest.Marshal(b, m, deterministic)
}
func (m *PlayedAIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayedAIRequest.Merge(m, src)
}
func (m *PlayedAIRequest) XXX_Size() int {
	return xxx_messageInfo_PlayedAIRequest.Size(m)
}
func (m *PlayedAIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayedAIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayedAIRequest proto.InternalMessageInfo

func (m *PlayedAIRequest) GetCurrentPlayerMove() *Node {
	if m != nil {
		return m.CurrentPlayerMove
	}
	return nil
}

type PlayedAIResponse struct {
	CurrentAIMove        *Node    `protobuf:"bytes,1,opt,name=currentAIMove,proto3" json:"currentAIMove,omitempty"`
	HelperPlayer         []*Node  `protobuf:"bytes,2,rep,name=helperPlayer,proto3" json:"helperPlayer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayedAIResponse) Reset()         { *m = PlayedAIResponse{} }
func (m *PlayedAIResponse) String() string { return proto.CompactTextString(m) }
func (*PlayedAIResponse) ProtoMessage()    {}
func (*PlayedAIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e21993b51421452, []int{5}
}

func (m *PlayedAIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayedAIResponse.Unmarshal(m, b)
}
func (m *PlayedAIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayedAIResponse.Marshal(b, m, deterministic)
}
func (m *PlayedAIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayedAIResponse.Merge(m, src)
}
func (m *PlayedAIResponse) XXX_Size() int {
	return xxx_messageInfo_PlayedAIResponse.Size(m)
}
func (m *PlayedAIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayedAIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayedAIResponse proto.InternalMessageInfo

func (m *PlayedAIResponse) GetCurrentAIMove() *Node {
	if m != nil {
		return m.CurrentAIMove
	}
	return nil
}

func (m *PlayedAIResponse) GetHelperPlayer() []*Node {
	if m != nil {
		return m.HelperPlayer
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector2Int)(nil), "grpcBuffer.Vector2Int")
	proto.RegisterType((*Node)(nil), "grpcBuffer.Node")
	proto.RegisterType((*InitGameRequest)(nil), "grpcBuffer.initGameRequest")
	proto.RegisterType((*InitGameResponse)(nil), "grpcBuffer.initGameResponse")
	proto.RegisterType((*PlayedAIRequest)(nil), "grpcBuffer.playedAIRequest")
	proto.RegisterType((*PlayedAIResponse)(nil), "grpcBuffer.playedAIResponse")
}

func init() { proto.RegisterFile("buffer.proto", fileDescriptor_1e21993b51421452) }

var fileDescriptor_1e21993b51421452 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0x99, 0xc7, 0x83, 0x57, 0x2e, 0xbc, 0x3c, 0xde, 0x2c, 0x48, 0x83, 0x2e, 0xc8, 0x2c,
	0x4c, 0x17, 0x86, 0x98, 0x6a, 0x5c, 0x9a, 0xe0, 0x86, 0x34, 0x46, 0x83, 0x63, 0xe2, 0x7e, 0x68,
	0x2f, 0x48, 0x02, 0x9d, 0x71, 0x3a, 0x10, 0xba, 0xf3, 0xaf, 0xf8, 0x4f, 0x4d, 0x87, 0x96, 0x52,
	0xc4, 0xe5, 0xe9, 0x3d, 0xfd, 0xee, 0xb9, 0x27, 0x03, 0x9d, 0xe9, 0x7a, 0x36, 0x43, 0x3d, 0x54,
	0x5a, 0x1a, 0x49, 0x61, 0xae, 0x55, 0x78, 0x6f, 0xbf, 0x30, 0x0f, 0xe0, 0x15, 0x43, 0x23, 0xb5,
	0x1f, 0xc4, 0x86, 0x76, 0x80, 0x6c, 0x5d, 0x32, 0x20, 0x5e, 0x83, 0x93, 0x6d, 0xa6, 0x52, 0xf7,
	0xd7, 0x4e, 0xa5, 0x2c, 0x86, 0xdf, 0x4f, 0x32, 0x42, 0xea, 0x83, 0xa3, 0x64, 0x32, 0xd2, 0x5a,
	0xa4, 0xd6, 0xda, 0xf6, 0x7b, 0xc3, 0x12, 0x38, 0x2c, 0x69, 0x7c, 0xef, 0xa3, 0x3d, 0x68, 0xaa,
	0xa5, 0x48, 0x51, 0xe7, 0xb8, 0x5c, 0xd1, 0x3e, 0x38, 0xa1, 0x50, 0x06, 0x35, 0x46, 0x6e, 0x7d,
	0x40, 0x3c, 0x87, 0xef, 0x35, 0x7b, 0x86, 0x7f, 0x8b, 0x78, 0x61, 0xc6, 0x62, 0x85, 0x1c, 0xdf,
	0xd7, 0x98, 0x18, 0x7a, 0x01, 0x8d, 0xa9, 0x14, 0x3a, 0x72, 0xc9, 0xa0, 0xee, 0xb5, 0xfd, 0xee,
	0xe1, 0xde, 0x2c, 0x1b, 0xdf, 0x8d, 0xb3, 0x75, 0x73, 0xb1, 0xc2, 0x20, 0xb2, 0xeb, 0x5a, 0x3c,
	0x57, 0xec, 0x12, 0xba, 0x25, 0x32, 0x51, 0x32, 0x4e, 0x90, 0xba, 0xf0, 0x67, 0x85, 0x49, 0x22,
	0xe6, 0x68, 0xaf, 0x69, 0xf1, 0x42, 0x66, 0x01, 0x6c, 0xcc, 0x68, 0x14, 0x14, 0x01, 0xee, 0xe0,
	0x7f, 0xb8, 0xd6, 0x1a, 0x63, 0x33, 0xb1, 0x07, 0x3c, 0xca, 0x0d, 0xda, 0x1d, 0xa7, 0xc2, 0x7c,
	0xb7, 0xb2, 0x0f, 0x02, 0xdd, 0x92, 0x99, 0x27, 0xb8, 0x85, 0xbf, 0xb9, 0x73, 0x14, 0x58, 0x20,
	0xf9, 0x01, 0x58, 0xb5, 0xd1, 0x1b, 0xe8, 0xbc, 0xe1, 0x52, 0xa1, 0x9e, 0x14, 0xd5, 0x9e, 0x2e,
	0xa5, 0xe2, 0xf2, 0x3f, 0x09, 0xb4, 0xb2, 0x3a, 0x5e, 0x50, 0x6f, 0x90, 0x8e, 0xc1, 0x29, 0x1a,
	0xa1, 0x67, 0x87, 0x7f, 0x1e, 0x55, 0xdf, 0x3f, 0x3f, 0x3d, 0xdc, 0x9d, 0xc0, 0x6a, 0xf4, 0x01,
	0x9c, 0xe2, 0xb0, 0x2a, 0xe8, 0xa8, 0xc2, 0x2a, 0xe8, 0xb8, 0x0b, 0x56, 0xf3, 0xc8, 0x15, 0x99,
	0x36, 0xed, 0x3b, 0xbd, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x45, 0x70, 0x04, 0x15, 0xb7, 0x02,
	0x00, 0x00,
}
